
#Common configuration settings
[common]
	#Mutant Zombie spawn weight
	#Range: 0 ~ 100
	mutantZombieSpawnWeight = 3
	#Mutant Skeleton spawn weight
	#Range: 0 ~ 100
	mutantSkeletonSpawnWeight = 3
	#Mutant Enderman spawn weight
	#Range: 0 ~ 100
	mutantEndermanSpawnWeight = 1
	#Affects spawn rate of all mutants
	#The smaller the number, the lower the chance
	#Range: 1 ~ 20
	globalSpawnRate = 5
	#Mutant Creeper spawn weight
	#Range: 0 ~ 100
	mutantCreeperSpawnWeight = 1

